// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ssixarpootajknctqrga.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNzaXhhcnBvb3RhamtuY3RxcmdhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg2OTUyNDQsImV4cCI6MjA3NDI3MTI0NH0.9S4f1tHvCQpEGtX14iHwT1uqP06uMoPA5rWmxu8MAkU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});