// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uqklhovluzjrdkmafgxe.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVxa2xob3ZsdXpqcmRrbWFmZ3hlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUzMTg1NTcsImV4cCI6MjA3MDg5NDU1N30.ebJ-XuVmS12OjFZ3uCz8-rHUdJq2XRmJETYq7iPpfA4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});